CREATE TABLE IF NOT EXISTS task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    description TEXT,
    status      VARCHAR(20) NOT NULL,
    created     TIMESTAMP   NOT NULL
);